### ISSUE TITLE
[Bug Report] Editors with different local default date formats cannot update the revision deadline.

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#546]
The date picker for revision deadlines seems to default to the computer's standard date format. However, the date is only accepted if this is dd/mm/yyyy format. Editors whos formats are dd.mm.yyyy mm/dd/yyyy or yyyy-mm-dd cannot update the dates. 

The result is "Please enter a valid date". Note this is in a standard javascript alert box, rather than a more themed modal or bootstrap error message.

See images below.

Expected behaviour:
 - Either the date should be accepted regardless of local date format and correctly converted, or 
 - The date picker should be forced to use the accepted format.

![dater-error-format](https://github.com/user-attachments/assets/9e5baa6b-3986-4d1c-b5b9-16d27a932f17)

![dater-error-format 2](https://github.com/user-attachments/assets/08bf56eb-8df1-49fc-8367-a6df7dbacd9a)

<img width="591" alt="dater-error-format 3" src="https://github.com/user-attachments/assets/9140fa96-923c-408d-baf1-517ff7ee39dd">

**Comment by JcharlesCCSD** [comment]
@davidjpurser Can you provide us, your browser and your operating system please 
Thank you in advance !

**Comment by davidjpurser** [comment]
Sorry, these reports are from several different editors that have had the issue. It works for me as my default system date is dd/mm/yy

**Comment by rtournoy** [comment]
I tried on Linux with both Chrome and Firefox, with all my locale settings changed for German. I was not able to reproduce the problem, the input format of the date picker does change depending on the system locale, but the component converts the local format to YYYY-mm-dd when the save button is used.

Do you think you can obtain more information on the operating system and browser used by the editors? we might be able to test with a more specific environment. I would also be interested to know if it happen with a manual input of the date or when using the calendar (both did work for me)

**Comment by davidjpurser** [comment]
Hi,

I received a reply from one of the three, and they were using Chrome and definitely used the date picker. Did say their OS, sorry.

Another editor experienced the issue today, using Brave on Mac OS (Sonoma) with English settings and produced the following screenshot when trying to add one month onto the revision deadline. They confirmed they clicked the date (november 6) using the date picker, not entering it themselves. 

![Image_9-10-24_at_16_07](https://github.com/user-attachments/assets/9e8b204a-b592-43d2-8944-ed192b603448)

**Comment by devletech** [comment]
It should work now

**Comment by davidjpurser** [comment]
Hi,
Sorry, but one of our editors told us they tried again after hearing it was fixed, and it still doesn't work for them, using Google Chrome on MacBook. Attached screen shot produced right now. 
![Unknown](https://github.com/user-attachments/assets/d54ef849-5fad-4f6d-b8dc-d61c5f0a50e6)

**Comment by devletech** [comment]
It is fixed online, thanks!
